In [1]:
import torch

In [99]:
torch.randint(-100, 100, (6,2))

tensor([[ 25, -35],
        [ 83, -11],
        [-30, -76],
        [-83,  77],
        [ -4, -78],
        [ 98, -69]])

In [10]:
torch.tensor([[0.1, 0.2],[0, 2.2]])

tensor([[0.1000, 0.2000],
        [0.0000, 2.2000]])

In [11]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
torch.ones(1,5)

tensor([[1., 1., 1., 1., 1.]])

In [13]:
torch.empty(2,3)

tensor([[1.3443e-23, 1.0748e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
torch.arange(7)

tensor([0, 1, 2, 3, 4, 5, 6])

In [20]:
torch.linspace(10, 50, 20)

tensor([10.0000, 12.1053, 14.2105, 16.3158, 18.4211, 20.5263, 22.6316, 24.7368,
        26.8421, 28.9474, 31.0526, 33.1579, 35.2632, 37.3684, 39.4737, 41.5789,
        43.6842, 45.7895, 47.8947, 50.0000])

In [23]:
torch.logspace(10, 20, 5)

tensor([1.0000e+10, 3.1623e+12, 1.0000e+15, 3.1623e+17, 1.0000e+20])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
torch.empty_like(torch.empty(5,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [50]:
probabilities = torch.tensor([0.1, 0.9,])
samples = torch.multinomial(probabilities, 10, replacement=True)
samples

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [53]:
torch.cat((torch.tensor([1,2,3,4]), torch.tensor([5])))

tensor([1, 2, 3, 4, 5])

In [58]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [59]:
torch.triu(torch.ones(5,5))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [68]:
torch.exp(torch.triu(torch.ones(5,4)))

tensor([[2.7183, 2.7183, 2.7183, 2.7183],
        [1.0000, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [72]:
torch.exp(torch.triu(torch.ones(5,4))).transpose(0,1)

tensor([[2.7183, 1.0000, 1.0000, 1.0000, 1.0000],
        [2.7183, 2.7183, 1.0000, 1.0000, 1.0000],
        [2.7183, 2.7183, 2.7183, 1.0000, 1.0000],
        [2.7183, 2.7183, 2.7183, 2.7183, 1.0000]])

In [74]:
torch.stack((torch.tensor([1,2,3]), torch.tensor([4,5,6]), torch.tensor([7,8,9])))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,False)
linear(sample)

tensor([ -7.5493, -10.2189,   5.0623], grad_fn=<SqueezeBackward4>)

In [93]:
nn.functional.softmax(torch.tensor([1.,2.,3.]), dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [95]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 6), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.2120, -1.9959, -1.0033,  0.3725, -0.9434,  1.0206],
        [-1.1342, -0.4808, -0.6626, -4.3180, -0.5789,  0.1155],
        [-0.4369, -0.2103, -0.4903, -1.1971,  0.6001, -1.1577],
        [ 0.7692, -0.6536, -1.3055,  1.0080, -1.9888, -1.0582]],
       grad_fn=<EmbeddingBackward0>)


In [98]:
a = torch.tensor([[1,2],[1,4]])
b = torch.tensor([[1,2, 4, 8],[1,4,2,3]])
a@b

tensor([[ 3, 10,  8, 14],
        [ 5, 18, 12, 20]])